controllers/categories.js
database/migrations/20220524144111-create-category.js
database/models/category.js

[OT198-18](https://alkemy-labs.atlassian.net/browse/OT198-18)
- Model fields:
id: INTEGER NOT NULL AUTO_INCREMENT
name: VARCHAR NOT NULL
description: VARCHAR NULLABLE
image: VARCHAR NULLABLE
timestamps y softDeletes
- Categories controller
- Create Category model
- After run `$ sequelize-cli db:migrate`

[CATEGORIES] OT198-18 Create Category model, migration and controller

---

controllers/organization.js
routes/index.js
routes/organization.js
services/organization.js

AS user
I WANT TO see the data of an organization
TO know about it
- A GET request must be made to the /organization/public route
- The endpoint must return only the name, image, phone and address fields of the Organization

[ENDPOINT] - Get organization/public - OT198-23

---

controllers/categories.js

- Change response success message
- Change 'e' by 'error' at catch

[FIX] OT198-41FIX Fix response message at categories controller

---

controllers/slide.js
routes/index.js
routes/slide.js
services/slide.js

Descripción
COMO usuario administrador
QUIERO ver el listados de Slides
PARA ver el contenido de forma gráfica.
Se debe hacer una petición GET a /Slides. 
Devolverá el listado de Slides, con la miniatura y el orden del mismo

[SLIDES] - Endpoint List Slides - OT198-57

---

controllers/user.js
routes/auth.js
schemas/user.js
services/user.js

[OT198-25](https://alkemy-labs.atlassian.net/browse/OT198-25)
AS user
I WANT to log into the system
TO access its functionalities
- A request of type POST /auth/login must be made
- The sending of the email and password fields in the request must be validated, and the password must be decrypted to authenticate
- Validate email and password on request
- Check if there is a user with the requested email
- If exists, compare encrypted password with password sent on request
- Return the user if it exists and the password is valid, if an error occurs, return {ok: false}
- happy path
- missing arguments
- user not found or incorrect password

[LOGIN] - Authentication Endpoint - OT198-25

---

controllers/user.js
routes/index.js
routes/user.js
services/user.js

[OT198-33](https://alkemy-labs.atlassian.net/browse/OT198-33)
AS a user
I WANT TO delete my user
SO THAT I can unsubscribe from the system
DELETE a /users/:id 
You should receive the user's id with the DELETE method. The deletion must be logical.
- Success case
- Not found
- Logic delete

[ ENDPOINT ] OT198-33 Delete User Endpoint

---

controllers/slide.js
routes/slide.js
services/slide.js

COMO usuario administrador
QUIERO ver el detalle de Slides
PARA ver el contenido de forma más detallada.
Se debe hacer una peticion GET a /Slides/:id . 
Mostrará todos los campos del slide en base al id enviado por parámetro. 
En el caso de que no exista, devolverá un error con un código de estado 404
**Success**
**404 Not Found**

[ENDPOINT] OT198-58 GET /Slides/Id

---

controllers/categories.js
routes/categories.js
services/categories.js

[OT198-45](https://alkemy-labs.atlassian.net/browse/OT198-45)
AS admin user
I WANT to delete an existing category
TO keep the information updated
DELETE /categories/:id - we must validate that the category exists and delete it, otherwise return an error
- Success case
- Not Found

[ENDPOINT] - DELETE /categories/:id - OT198-45

---

config/auth.js
middlewares/auth.js
middlewares/jwt.js
package.json
routes/index.js

[OT198-26](https://alkemy-labs.atlassian.net/browse/OT198-26)
AS authenticated user
I WANT to restrict access to certain content
TO keep data protected
It should check if the request contains the token corresponding to a user, otherwise it should return an error code 403 with an error message.

[MIDDLEWARE] Ot198 26 - Middleware for Authenticated Users

---

controllers/user.js
routes/index.js
routes/user.js
services/user.js

Descripción
COMO usuario 
QUIERO actualizar mis datos
PARA modificar mi perfil
PATCH a /users/:id. En el caso de que el usuario no exista, devolverá un error 404.
user register
user updated
user not found - 404

[ENDPOINT] OT198-35 Endpoint User Update

---

middlewares/isAdmin.js

AS Admin user
I WANT TO restrict access to certain content
TO keep data protected
- Must verify the roleId field, and allow to continue if the user has a role corresponding to administrator

[MIDDLEWARE] OT198-27 Middleware for Admin users

---

templates/welcomeEmail.js

[OT198-30](https://alkemy-labs.atlassian.net/browse/OT198-30)
AS user
I WANT TO receive a welcome email when registering
SO THAT I can make sure the registration happened correctly. 
When the user registers on the site, a welcome email will be sent. It must contain the logo and name of the Organization, a welcome text and contact information.
- Template email sent

[ TEMPLATE ] OT198-30 Create Welcome Email Template

---

controllers/categories.js
routes/categories.js
services/categories.js

[OT-198-44](https://alkemy-labs.atlassian.net/jira/software/c/projects/OT198/boards/278?modal=detail&selectedIssue=OT198-44)
AS admin user
I WANT to modify an existing category
TO keep the information updated
PUT /categories/:id - It must validate that the category exists and update it, otherwise return an error
STATUS OK
NOT FOUND

[ENDPOINT] UPDATE CATEGORIES OT-198-44

---

controllers/user.js
routes/user.js
services/user.js

[OT198-36](https://alkemy-labs.atlassian.net/browse/OT198-36)
AS Admin user
I WANT TO view a list of users
TO keep track of who is part of the system
- GET to /users . It will return a list of all Users. This endpoint should only be accessible by admin Users.

[ENDPOINT] OT198-36 Endpoint user get

---

config/auth.js
services/user.js

[OT198-32](https://alkemy-labs.atlassian.net/browse/OT198-32)
AS user
I WANT to be authenticated on the platform
TO be able to access all its services.
When the user is authenticated, the server must generate a JSON Web Token with the user's data, and return it in the response.
To validate that the user is authenticated, the server must decrypt this token, obtaining it from the Authorization header of the received request.
Suggested library: https://www.npmjs.com/package/jsonwebtoken

[TOKEN-AUTH] Token generation on authentication

---

libs/s3Client.js
package.json
services/s3Service.js

[OT198-39](https://alkemy-labs.atlassian.net/browse/OT198-39)
AS admin user
I WANT to upload images in the system
SO THAT I can improve communication
The Amazon S3 file management service must be linked through its SDK for Node.js. It will be used later for fields of different entities, such as the user's profile photo, NGO logo, blog images and others, so a reusable service must be created for file management.

[ SERVICE ] OT198-39 Setup Amazon S3 SDK

---

controllers/organization.js
routes/organization.js
schemas/organization.js
services/organization.js

[OT198-38](https://alkemy-labs.atlassian.net/browse/OT198-38)
AS Admin user
I WANT TO update the public data of the Organization
TO keep information updated
- POST request to route /organization/public
- Only the administrator user can edit the public data of the Organization. You must validate the required fields and their correct format
-

[ENDPOINT] OT198-38 Update organization public data

---

services/sendgrid.js
services/user.js

[OT198-31](https://alkemy-labs.atlassian.net/browse/OT198-31)
AS user
I WANT to see a welcome email when I register
TO make sure the registration happened correctly.
- Use the email sending service and the welcome template to programmatically send an email when a user registers, to the email they provided in their registration
- Success registration
- When fail to register
if the email is used the server throw error 500 and the sendgrid function is never called

[SENDGRID] -  Welcome email sending - OT198-31

---

controllers/news.js
routes/news.js
services/news.js

COMO usuario administrador
QUIERO actualizar una novedad existente
PARA poder mantener a información actualizada
PUT /news/:id - Deberá validar que la novedad exista en base al id enviado por parámetro. En el caso de que no exista devolver un error, caso contrario actualizar la novedad y devolver la misma con los datos actualizados

[ENDPOINT] OT198-48 Create Endpoint Update News

---

database/migrations/20220524011902-create-activity.js
database/models/activity.js
database/seeders/20220601145321-activities.js

[OT198-54](https://alkemy-labs.atlassian.net/browse/OT198-54)
AS a user
I WANT to visualize the existing data of the NGO
TO keep the information updated
From the existing data in the case of the NGO, create a seeder that allows these data to be populated in the database.

[SEED] - Create Activities seeder OT198-54

---

controllers/contacts.js
routes/contacts.js
routes/index.js
services/contacts.js

[OT198-63](https://alkemy-labs.atlassian.net/browse/OT198-63)
AS user
I WANT to list the contacts of the page
TO be able to see all that exist
GET /contacts - Will return all contact records. This endpoint can only be accessed by an administrator user

[ENDPOINT] Get Contacts - OT198-63 

---

controllers/testimonial.js
routes/index.js
routes/testimonial.js
schemas/testimonial.js
services/testimonial.js

[OT198-69](https://alkemy-labs.atlassian.net/browse/OT198-69)
AS admin user
I WANT to register new Testimonials
TO inform News about the NGO.
POST /testimonials - we must validate the existence of the sent name and content fields, to store the record in the testimonials table.
The validation that the user is an administrator and the scheme are done in the middlewares
- happy path
- wrong / missing body

[ENDPOINT] - Create Testimonial - OT198-69

---

controllers/news.js
routes/news.js
services/news.js

[OT198-50](https://alkemy-labs.atlassian.net/browse/OT198-50)
AS admin user
I WANT to delete an existing activity
TO keep the information updated
DELETE /news/:id - need to validate the existence based on the id sent by parameter. If it exists, remove it.
The verification that the user is admin is done by the middleware
- happy path
- not found

[ENDPOINT] - Delete A New - OT198-50

---

libs/s3Client.js
middlewares/uploadImage.js
middlewares/validateErrors.js
package.json
services/uploadImageToS3.js

[OT198-40](https://alkemy-labs.atlassian.net/browse/OT198-40)
AS admin user
I WANT to upload images in the system
TO improve communication
It should be integrated with existing methods that handle images. It will take care of storing an image in Amazon and returning the absolute path to the bucket

Upload Images OT198-40

---

controllers/slide.js
routes/slide.js
schemas/slide.js
services/slide.js

[OT198-60](https://alkemy-labs.atlassian.net/browse/OT198-60)
AS admin user
I WANT to be able to update Slides
TO have the updated information at the top of the page
- A PUT /Slides/:id request must be made
- must validate that the slide exists and update it, otherwise return an error.
auth, admin and schema validations are done by middleware
- PUT /slides/:id happy path
-PUT /slides/:id not found

[ENDPOINT] - Slides update route, controller and service and schema - OT198-60

---

services/organization.js

[OT198-67](https://alkemy-labs.atlassian.net/browse/OT198-67)
AS user
I WANT to see the links of social networks when entering the page
to be able to access them.
When returning the data on the public data endpoint, add the social network fields in the response

[ENDPOINT] Modify organizations public endpoint OT198-67

---

controllers/testimonial.js
routes/testimonial.js
services/testimonial.js

[OT198-71](https://alkemy-labs.atlassian.net/browse/OT198-71)
AS admin user
I WANT to delete Testimonials
TO moderate Testimonials and News about the ONG.
DELETE /:id to delete a testimonial or if not found, return 404 Not Found
- DELETE /id happy path
- DELETE /id not found

[ENDPOINT] - Delete Testimonial endpoint - OT198-71

---

controllers/testimonial.js
routes/testimonial.js
schemas/testimonial.js
services/testimonial.js

[OT198-70](https://alkemy-labs.atlassian.net/browse/OT198-70)
AS admin user
I WANT to update Testimonials
TO report new news about the ONG.
PUT /testimonials/:id - we were able to validate that the news exists based on the id sent by parameter. In the event that it does not exist, it must return an error, while otherwise, it must update it and return it with the new data.
- PUT /testimonials/:id happy path
the image is saved with the name slide-****.png because there is a problem in the middleware that uploads it to the temporary folder
- PUT /testimonials/:id not found

[ENDPOINT] - Update testimonial  - OT198-70

---

controllers/user.js
services/user.js

[OT198-51](https://alkemy-labs.atlassian.net/jira/software/c/projects/OT198/boards/278?modal=detail&selectedIssue=OT198-51)
AS authenticated user
I WANT to get an authentication token
TO keep me logged in the system
When the user registers on the site, he must log in automatically. To do this, it is necessary to modify the registration endpoint so that it returns the token once the user is created, since it will be stored on the client side

[USER TOKEN] - OT198-51 - Return token to user after registering on the site

---

controllers/slide.js
routes/slide.js
services/slide.js

[OT198-61](https://alkemy-labs.atlassian.net/browse/OT198-61)
AS admin user
I WANT TO be able to remove Slides
SO THAT I can have the updated information at the top of the page
A DELETE /Slides/:id request must be made
You must validate that the slide exists and delete it, otherwise return an error.
- Success case
- Error not admin user 
- Error token validation
- Error Slide not found

[ ENDPOINT ] OT198-61 Delete Slide Endpoint

---

controllers/members.js
routes/index.js
routes/members.js
schemas/member.js
services/members.js

[OT198-74](https://alkemy-labs.atlassian.net/browse/OT198-74)
COMO usuario
QUIERO crear un miembro
PARA actualizar la información de la web.
POST /members - Deberá validar que se envíe el campo name, y el mismo sea un string
Success:
Error:

[ENDPOINT] Create Endpoint post Members

---

controllers/testimonial.js
routes/testimonial.js
services/testimonial.js

add image upload service to testimonial service

[FIX] - Add upload image service when create a testimonial

---

controllers/comments.js
routes/comments.js
routes/index.js
services/comments.js

[OT198-80](https://alkemy-labs.atlassian.net/browse/OT198-80)
AS admin user
I WANT to get a list of Comments
TO moderate the same.
GET /comments - Will return all Comments, ordered by creation date, only the body field

[ENDPOINT] Get comments - OT198-80

---

database/migrations/20220606175607-create-comment.js
database/models/comment.js
database/models/new.js
database/models/user.js

[OT198-51](https://alkemy-labs.atlassian.net/jira/software/c/projects/OT198/boards/278?modal=detail&selectedIssue=OT198-51)
AS user
I WANT to add a new comment to a post
TO comment on this post.
The ability to add Comments to a News post will be added. The fields of a comment will be user_id, body and new_id

[COMMENTS] OT198-79 create model and migration

---

controllers/members.js
routes/index.js
routes/members.js
services/members.js

[OT198-73](https://alkemy-labs.atlassian.net/browse/OT198-73)
COMO administrador
QUIERO listar los Miembros
PARA obtener información certera de los Miembros al día.
GET /members - Devolverá todos los Miembros
Success:
Error when auth but not admin:

[ENDPOINT] OT198-73 get Members, create routes, service, and refactor controller

---

controllers/slide.js
routes/slide.js
schemas/slide.js
services/slide.js

Descripción
COMO usuario administrador
QUIERO poder crear Slides 
PARA agregar más información al comienzo de la pagina
Criterios de aceptación: 
Se debe hacer una peticion POST /Slides 
Recibirá la imágen a almacenar en base 64. La misma deberá ser decodeada y almacenada en Amazon S3. 
En el caso de no recibir el campo order, deberá establecer el mismo como el último en base a los existentes
post with order
post without order
post fail

[MODELS] create slides controller, services and schema OT198-59

---

controllers/comments.js
routes/comments.js
schemas/comment.js
services/comments.js

[OT198-81](https://alkemy-labs.atlassian.net/browse/OT198-81)
AS user
I WANT to register new Comments
SO THAT I can add them to an existing post
POST /comments - You will need to validate that the newId, userId and body fields are sent.
- Success case
- Validation error
- No authorization header
- Error userId/newId not found

[ ENDPOINT ] OT198-81 Create Comments Endpoint

---

routes/index.js

redirect to /api/docs if route no exists

[REDIRECT] - redirect to /api/docs if route no exists

---

controllers/members.js
routes/members.js
schemas/member.js
services/members.js

[OT198-76](https://alkemy-labs.atlassian.net/browse/OT198-76)
AS user
I WANT to update Members
SO THAT I keep the information updated.
PUT /members/:id - It must validate that the member exists and update it, otherwise return an error
- Success case
- Update without image
- ID not found:

[ ENDPOINT ]OT198-76 Update Members Endpoint

---

constants/roles.js
database/seeders/20220607144743-users.js
middlewares/isAdmin.js
middlewares/ownership.js
services/comments.js
services/user.js

- Create a constant for user's roles and replace it where it needs.
- Add default Standard rol user when create a new user.

[ FIX ] OT198-FIX-USER Create Roles Constant

---

routes/contacts.js
test/contact.test.js

[OT198-100](https://alkemy-labs.atlassian.net/browse/OT198-100)
AS a developer
I WANT to have tests of the /contact endpoints
TO ensure the integrity and operation of the project
Test the correct response scenario, and error scenarios, such as non-existent ids, validations, permissions, etc. The file must be created inside the /test folder, with the same name as the endpoint. The test created as a demonstration can be used as a basis.
- Evidence:

[TESTING] OT198-100 Test endpoints contacts

---

routes/members.js

[OT198-92](https://alkemy-labs.atlassian.net/browse/OT198-92)
AS a developer
I WANT to have a documentation of the Member's endpoints
SO THAT I have references of its operation
The different endpoints must be documented, specifying the data model, mandatory fields, request format and its example.
- Post route
- Get route
- Put route
- Delete route

[ SWAGGER ] Add Member Documentation

---

test/auth.test.js

[OT198-101](https://alkemy-labs.atlassian.net/browse/OT198-101)
AS a developer
I WANT to have tests of /authentication endpoints
SO THAT I can ensure the integrity and operation of the project
Test the correct response scenario, and error scenarios, such as non-existent ids, validations, permissions, etc. The file must be created inside the /test folder, with the same name as the endpoint. The test created as a demonstration can be used as a basis.

[ TEST ] OT198-101 Test: Endpoints /authentication

---

controllers/news.js
routes/news.js
services/news.js

- Add upload image implementation when create a news or update it.

[ FIX ] OT198-FIX-NEWS Add uploadImage in News

---

database/migrations/20220524285715-create-new.js

model case changes for some old mysql databases that are case sensitive

[MIGRATIONS] - small migration fix to news migration
